spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carport?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jxq016255
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.itwanli: info
  file: log/blog-pro.log
server:
  port: 8081



