spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carport?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: ENC(t0SVrZzqHZgvKwwHeK/D6GIA122FQc/w)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.itwanli: info
  file: log/blog-pro.log
server:
  port: 8081

#数据库密码加密配置
jasypt:
  encryptor:
    password: ZwqMysqlPassword


