spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carport?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: jxq016255
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.itwanli: debug
  file: log/blog-dev.log



